import QtQuick 2.15

QtObject{
    property string brandColor: "#177ddc"
    property string darkerTransBrandColor: "#a0177ddc"
    property string semiTransBrandColor: "#80177ddc"
    property string lighterTransBrandColor: "#50177ddc"
    property string primaryColor: "#333"
    property string secondaryColor: "#555"
    property string lightColor: "#777"
    property string lighterColor: "#999"
    property string successColor: "#67c23a"
    property string warningColor: "#e6a23c"
    property string dangerColor: "#f56c6c"
    property string semiTransSuccessColor: "#8067c23a"
    property string semiTransWarningColor: "#80e6a23c"
    property string semiTransDangerColor: "#80f56c6c"
    property string primaryFontColor: "#fff"
    property string regularFontColor: "#dcdcdc"
    property string secondaryFontColor: "#ccc"
    property string placeholderFontColor: "#aaa"
    property string baseBorderColor: "#ccc"
    property string lightBorderColor: "#bbb"
    property string lighterBorderColor: "#aaa"
    property string extraBorderColor: "#999"
    property string backgroundColor: "#333"
    property string lightBackgroundColor: "#444"
    property string lighterBackgroundColor: "#555"
    property string primaryDisableColor: "#777"
    property string secondaryDisableColor: "#999"
    property string fullTransparentColor: "#00000000"
    property string halfTransparentColor: "#50000000"
}
